// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoWeb24AM.Context;

#nullable disable

namespace ProyectoWeb24AM.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231130215734_example")]
    partial class example
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Articulo", b =>
                {
                    b.Property<int>("PKArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKArticulo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrlImagenPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKArticulo");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Libro", b =>
                {
                    b.Property<int>("PKLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKLibro"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKLibro");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Promocion", b =>
                {
                    b.Property<int>("PKPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKPromocion"));

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FkArticulo")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagenPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKPromocion");

                    b.HasIndex("FkArticulo");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Rol", b =>
                {
                    b.Property<int>("PKRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PKRol = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            PKRol = 2,
                            Nombre = "SA"
                        });
                });

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("PKUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FKRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKUsuario");

                    b.HasIndex("FKRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            PKUsuario = 1,
                            Apellido = "Dzul",
                            FKRol = 1,
                            Nombre = "Jacob",
                            Password = "1501",
                            UserName = "MurderBunny"
                        });
                });

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Promocion", b =>
                {
                    b.HasOne("ProyectoWeb24AM.Models.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("FkArticulo");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("ProyectoWeb24AM.Models.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoWeb24AM.Models.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FKRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
